### PR TITLE
Fast read multi topology

### PR DESCRIPTION
**Pull request by gaballench**
I am including a version of `readMultiTopology` (named `readMultiTopologyFast`) which uses `Functors.fmap` for mapping `readTopology` over a vector of newick topologies. It includes a docstring, modifications necessary in `Project.toml`, `scr/PhyloNetworks.jl`, and unit tests. The tests are passing with `Pkg.test("PhyloNetworks")` in develop mode. This relates to #170, probably closing it.

### CODE REVIEW

**Comment by cecileane** [comment]
Thanks for this PR! I have a few suggestions, to make this change more user-friendly.

- It would be more friendly to have a single function `readMultiTopology` instead of separate 2 functions (`readMultiTopology` and `readMultiTopologyFast`).
  * Could the fast version be obtained with an extra (positional) argument?
  * In that case, could the argument to use the fast version be the default, since it's better?
  The main difficulty might be to write 2 methods: the current method that takes in a vector of strings (or better: `Vector{<:AbstractString}` perhaps), and another method that takes a single string (or a single `AbstractString`), which would be the file name in that case. The current `readMultiTopology` takes a single string (file name) as input.
 
- It would be great if the docstring could give an example, ideally tested with the doc tests (that is, inside a `jldoctest` block)

**Comment by gaballench** [comment]
Hello Dr. Ané. Thanks for your suggestions. I totally agree in that it would be cleaner to have a single function but preferred to act conservatively by suggesting a different function so that no compatibility issues could arise.

I will try to implement your suggestions on methods and reintroduce the example in the docstring which I already have but removed during testing because something was not working properly and I forgot to include it back.

**Comment by gaballench** [comment]
Hello Dr. Ané,

In the commit e01819a9de20c7731b49fa0ac2b19ff3e8ee113b I have included the `jldoctest` block, and the definitions of four methods (`fast` is a named argument in contrast to `topologies`): 

- `topologies::AbstractString; fast=true`: path to file, read with `readlines` and then using `Functors.fmap`
- `topologies::AbstractString; fast=false`: path to file, read topologies, original code of `readMultiTopology`.
- `topologies::Vector{<:AbstractString}; fast=true`: vector of newick strings, read using `Functors.fmap`
-  `topologies::Vector{<:AbstractString}; fast=false`: vector of newick strings, read using `map(readTopology, topologies)` 

Changes were necessary in `test/test_bootstrap.jl` and `test/test_readInputData.jl`. Both tests are passing correctly. I have added tests to check that the four different methods are equivalent for reading the same information, whether starting from a path to file or a vector of newick strings.

This should solve your earlier suggestions.

Best wishes,

Gustavo

**Comment by cecileane** [comment]
Thanks! I modified the code because having 2 methods with the same signature didn't work. Only 1 method was used regardless of the `fast` option. I added an `@info` statement so we can see when the legacy function is used. This is meant to be removed!

I also changed the tests to use the default all the time, except when testing `readMultiTopology` itself, and I simplified those tests. (Writing a topology to `stdout` writes the topology to the screen instead of returning a string and the returned object is `nothing`, so I modified some of the tests accordingly.)

In the docstring, I changed the example block to be a simple julia block, not "jldoctest" because otherwise the block would have to contain the entire output... which would be overly long with 25 topologies multiple times. Sorry for suggesting a "jldoctest" earlier.

**Comment by cecileane** [comment]
I just cleaned up an info statement. It's ready to be merged. Thanks @gaballench !

**Pull request merged**
