### PR TITLE
gradient-based optimization of branch lengths

### PR DESCRIPTION
**Pull request by cecileane**
using NLopt (LD_SLSQP method), co-authored by by Jingcheng Xu.

@jokeitei and @coraallensavietta: the use of `dot(x,A,y)` for the log-likelihood and gradient calculations requires julia v1.4. I removed 1.1-1.3 in `Project.toml`. Are you against this? as I see it:
- downside: folks using julia on a cluster might not have julia 1.4 on their cluster yet, and would have to go through the trouble of asking for it to their cluster administrator. 
- upside: the dot function is probably highly efficient. Julia is getting used more and more, so cluster administrators are probably getting more familiar with Julia. On laptops, upgrading julia is a piece of cake.

I'm interested to hear what you think.

### CODE REVIEW

**Comment by coraallensavietta** [comment]
I think this is a great idea. It sounds like the benefits of using the dot function outweigh the potential hassle of upgrading to 1.4.

**Comment by cecileane** [comment]
The documentation build failed: see [here](https://travis-ci.org/github/crsl4/PhyloNetworks.jl/jobs/688905229#L979). The error occurs within a function evaluation within an `NLopt.Opt` object, so it's caught and fails silently. Within that function, the problem is with the `dot()` function. The version from the `Optim` package seems to be called, instead of the version from `LinearAlgebra`. See this below, which looks terrible: the output of `dot([1,3],[1 2; 3 4], [2,3])` is different before and after we do `using PhyloPlots`. It's good before. It's an error after.

What do you suggest? Just avoid `dot` for now?

```julia
julia> using Pkg; Pkg.status()
Status `~/.julia/dev/PhyloNetworks/docs/Project.toml`
  [3c28c6f8] BioSymbols v3.1.0
  [336ed68f] CSV v0.6.1
  [a93c6f00] DataFrames v0.20.2
  [e30172f5] Documenter v0.24.11
  [997ab1e6] DocumenterMarkdown v0.2.0
  [33ad39ac] PhyloNetworks v0.11.0 [`~/.julia/dev/PhyloNetworks`]
  [c0d5b6db] PhyloPlots v0.2.2 #master (https://github.com/cecileane/PhyloPlots.jl.git)
  [6f49c342] RCall v0.13.4
  [2913bbd2] StatsBase v0.33.0
  [3eaba693] StatsModels v0.6.11
  [37e2e46d] LinearAlgebra 

julia> using PhyloNetworks

julia> PhyloNetworks.LinearAlgebra.dot([1,3],[1 2; 3 4], [2,3]) # 62
62

julia> using PhyloPlots # precompilation warnings, linked to dot from LinearAlgebra being overwritten in Optim

julia> PhyloNetworks.LinearAlgebra.dot([1,3],[1 2; 3 4], [2,3])
ERROR: MethodError: no method matching similar(::Int64)
Closest candidates are:
  similar(::DataFrames.StackedVector, ::Type, ::Union{Integer, AbstractUnitRange}...) at /Users/ane/.julia/packages/DataFrames/S3ZFo/src/abstractdataframe/reshape.jl:329
  similar(::Array{T,1}) where T at array.jl:356
  similar(::Array{T,2}) where T at array.jl:357
  ...
Stacktrace:
 [1] dot(::Int64, ::Int64, ::Int64) at /Users/ane/.julia/packages/Optim/tAcSy/src/multivariate/precon.jl:23
 [2] dot(::Array{Int64,1}, ::Array{Int64,2}, ::Array{Int64,1}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/LinearAlgebra/src/generic.jl:928
 [3] top-level scope at REPL[5]:1

julia> using LinearAlgebra

julia> LinearAlgebra.dot([1,3],[1 2; 3 4], [2,3]) # same error
ERROR: MethodError: no method matching similar(::Int64)
Closest candidates are:
  similar(::DataFrames.StackedVector, ::Type, ::Union{Integer, AbstractUnitRange}...) at /Users/ane/.julia/packages/DataFrames/S3ZFo/src/abstractdataframe/reshape.jl:329
  similar(::Array{T,1}) where T at array.jl:356
  similar(::Array{T,2}) where T at array.jl:357
  ...
Stacktrace:
 [1] dot(::Int64, ::Int64, ::Int64) at /Users/ane/.julia/packages/Optim/tAcSy/src/multivariate/precon.jl:23
 [2] dot(::Array{Int64,1}, ::Array{Int64,2}, ::Array{Int64,1}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/LinearAlgebra/src/generic.jl:928
 [3] top-level scope at REPL[7]:1
```

**Comment by cecileane** [comment]
also, from the manifest, it was using `Optim v0.20.1` above. I don't know which package (required by `PhyloPlots`) holds `Optim` back. But `Optim` by itself is not the problem. When we require `LinearAlbegra` and `Optim v0.20.1` only, there is not problem with `dot`:
```julia
(@v1.4) pkg> status
Status `~/.julia/environments/v1.4/Project.toml`
  [429524aa] Optim v0.20.1
  [37e2e46d] LinearAlgebra 

julia> using LinearAlgebra

julia> dot([1,3],[1 2; 3 4], [2,3])
62

julia> using Optim

julia> dot([1,3],[1 2; 3 4], [2,3])
62
```

Adding `DataFrames@v0.20.2` does not cause the problem to resurface either.

**Comment by cecileane** [comment]
my bad: the `dot` error above, when using PhyloPlots, had `Optim v0.19.3` in the manifest. With that earlier version of `Optim`, we can reproduce the error simply:

```julia
(@v1.4) pkg> status
Status `~/.julia/environments/v1.4/Project.toml`
  [429524aa] Optim v0.19.3
  [37e2e46d] LinearAlgebra 

julia> using LinearAlgebra

julia> dot([1,3],[1 2; 3 4], [2,3])
62

julia> using Optim

julia> dot([1,3],[1 2; 3 4], [2,3])
ERROR: MethodError: no method matching similar(::Int64)
Closest candidates are:
  similar(::Array{T,1}) where T at array.jl:356
  similar(::Array{T,2}) where T at array.jl:357
  similar(::Array{T,1}, ::Type) where T at array.jl:358
  ...
Stacktrace:
 [1] dot(::Int64, ::Int64, ::Int64) at /Users/ane/.julia/packages/Optim/tAcSy/src/multivariate/precon.jl:23
 [2] dot(::Array{Int64,1}, ::Array{Int64,2}, ::Array{Int64,1}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/LinearAlgebra/src/generic.jl:928
 [3] top-level scope at REPL[7]:1
```

So I see these options for us:
- avoid `dot`, and/or
- remove from `PhyloPlots` these bad dependencies. I have the vague feeling that Gadfly is what's requiring a lot of things, some of which may not be maintained. It's not just holding `Optim` back. It's also affecting important packages like `StatsBase`. If we remove `Gadfly`, plots would rely on `RCall` only.

I'm interested to know what you think, @jokeitei and @coraallensavietta .

**Comment by coraallensavietta** [comment]
> my bad: the `dot` error above, when using PhyloPlots, had `Optim v0.19.3` in the manifest. With that earlier version of `Optim`, we can reproduce the error simply:
> 
> ```julia
> (@v1.4) pkg> status
> Status `~/.julia/environments/v1.4/Project.toml`
>   [429524aa] Optim v0.19.3
>   [37e2e46d] LinearAlgebra 
> 
> julia> using LinearAlgebra
> 
> julia> dot([1,3],[1 2; 3 4], [2,3])
> 62
> 
> julia> using Optim
> 
> julia> dot([1,3],[1 2; 3 4], [2,3])
> ERROR: MethodError: no method matching similar(::Int64)
> Closest candidates are:
>   similar(::Array{T,1}) where T at array.jl:356
>   similar(::Array{T,2}) where T at array.jl:357
>   similar(::Array{T,1}, ::Type) where T at array.jl:358
>   ...
> Stacktrace:
>  [1] dot(::Int64, ::Int64, ::Int64) at /Users/ane/.julia/packages/Optim/tAcSy/src/multivariate/precon.jl:23
>  [2] dot(::Array{Int64,1}, ::Array{Int64,2}, ::Array{Int64,1}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/LinearAlgebra/src/generic.jl:928
>  [3] top-level scope at REPL[7]:1
> ```
> 
> So I see these options for us:
> 
> * avoid `dot`, and/or
> * remove from `PhyloPlots` these bad dependencies. I have the vague feeling that Gadfly is what's requiring a lot of things, some of which may not be maintained. It's not just holding `Optim` back. It's also affecting important packages like `StatsBase`. If we remove `Gadfly`, plots would rely on `RCall` only.
> 
> I'm interested to know what you think, @jokeitei and @coraallensavietta .

Hmm, this is a hard one. On the one hand, I'm all for dropping bad dependencies. Plus, I tend to use RCall for PhyloPlots anyway. On the other hand, this could be a large refactor for PhyloPlots and also cause it to lose some functionality. How large of a change to PhyloPlots would this be, @cecileane ?

**Comment by cecileane** [comment]
Dropping `Gadfly` plots in `PhyloPlots` should not be very hard, because the 2 kinds of plots have been well separated. An earlier version had `RCall`-based plots only, until I took the time to add Gadfly back.

The last commit dropped `dot`, and it wasn't a big change because it was used in 1 place only. We can still worry about `PhyloPlots` later.

**Pull request merged**
