### PR TITLE
Minor fixes: added 2 spaces and QuartetNetwork docstring

### PR DESCRIPTION
**Pull request by crsl4**
- Adding 2 spaces that were removed by emacs in [this commit](https://github.com/crsl4/PhyloNetworks.jl/commit/1da33251d9c92dff82f9e994a98eee1a9004d646#diff-bf74838e012760cf4d61d1346156dd9dR1862)
- Created the docstring for QuartetNetwork

### CODE REVIEW

**Comment by cecileane** [comment]
This is unrelated to the docstring, but it would be good to include a formal test for the changes to `writeTopologyLevel1` and to the end of `snaq!`, in 3e079e6 .

By the way, the chunk of code repeated in `writeTopologyLevel1` and in `snaq!` could possibly be move to `checkRootPlace!`: That way, there is less room for bugs (e.g. bug fixed in one place but not in the other, when the chunk is repeated), and the code for both `writeTopologyLevel1` and in `snaq!` would be cleaner. The formal test could also be made cleaner that way.

**Comment by crsl4** [comment]
yes, I agree! There is a lot of things that I want to re-write on this checkRoot situation. It is in my to-do list, but it needs some time to sit down and focus that I have not had. I will put my notes on an issue.

**Comment by cecileane** [comment]
just to see how coverage had decreased after adding the two chunks to check that root is admissible: on [codecov](https://codecov.io/gh/crsl4/PhyloNetworks.jl/commit/1da33251d9c92dff82f9e994a98eee1a9004d646)

**Comment by cecileane** [comment]
To get more detail on code that was added but is not covered during testing: [see in `readwrite.jl`](https://codecov.io/gh/crsl4/PhyloNetworks.jl/src/637e26f82c299eaf09011d89bb8269bfd5f9f527/src/readwrite.jl) and [in `snaq_optimization.jl`](https://codecov.io/gh/crsl4/PhyloNetworks.jl/src/637e26f82c299eaf09011d89bb8269bfd5f9f527/src/snaq_optimization.jl). The code coverage is really poor for some files, so I find it important to do better with new code.

I need to fix a bug in the function that direct edges, because that function should return an error if the network is not a DAG. I would like to work from a clean `master` branch with this current PR finished. Could you please help @crsl4?

**Comment by cecileane** [comment]
We also need to take care of the DataStructure update (PR #137). I would love for this PR to be finished, and make progress on the other things.

**Comment by crsl4** [comment]
Sorry Cecile! I was waiting for you to merge the pull request. I got lost whether there was something missing here. By reading again, are we mainly missing the `writeTopologyLevel1` tests? Do we want to include them in this PR or could we merge the PR and do the tests later?

**Comment by cecileane** [comment]
Yes we should include them in this PR. Otherwise, we will never do it. We should also fix the documentation errors (Travis says "it's all good" in its summary, but when we look at what happened, there were errors.) I'm working on fixing the doc errors right now.

**Comment by cecileane** [comment]
It looks like the random number generator has changed, in julia v1.4 vs v1.5... causing more errors in the doc. and probably a lot more in the tests...

**Comment by crsl4** [comment]
ok! to make sure I am on the same page: we need a test for the new `writeTopologyLevel1` or a test that covers the new lines added at the end of snaq (or both)?

**Comment by cecileane** [comment]
both ideally.

I see that the tests are broken with julia v1.5, see starting [here](https://travis-ci.org/github/crsl4/PhyloNetworks.jl/jobs/724539245#L550) (including a conflict between our own `rotate!` and `LinearAlgebra.rotate!`. Should we re-name to `rotate edges!`?). Some of the tests that failed with bootsnaq are concerning too.

**Comment by cecileane** [comment]
ahh.. the tests that were affected by the change in the RNG pass on julia v1.5 but break on julia v1.4, or vice versa. So we can't ask Travis to test both under julia v1.4 and v1.5 successfully. I would like to cancel the tests that are currently running (for commit e60f7f6) but I don't have permission.

**Comment by crsl4** [comment]
sorry that you do not have permission to cancel them! I think we tried before to give you these permissions, but I cannot find the option in travis.

sorry also that I am getting a bit lost (and slow) in this PR! I will pull your changes, and add the new tests. Please let me know if I am missing something

**Comment by crsl4** [comment]
@cecileane how do I know if the coverage increased with these two new commits? I added the tests and tested locally on julia 1.5. But I do not know how to check the coverage.

**Comment by cecileane** [comment]
After all the tests are done, you can go over to [coveralls](https://coveralls.io/github/crsl4/PhyloNetworks.jl) for PhyloNetworks, say, then pick a commit that was tested, follow the link to know more about coverage and coverage change due to this commit [like here](https://coveralls.io/builds/33266670), then click on any file (like [readwrite](https://coveralls.io/builds/33266670/source?filename=src%2Freadwrite.jl#L13))to see the changes to this file, and what's covered or not.

[Codecov](https://codecov.io/gh/crsl4/PhyloNetworks.jl) has another report, which I find a little easier to use. Like [here](https://codecov.io/gh/crsl4/PhyloNetworks.jl/pull/135) for the current pull request. (click on Files then browse to see coverage for each file).

**Review by cecileane — APPROVED** [review]
looks good to me, thank you @crsl4!

**Pull request merged**
