### PR TITLE
implementing multivariate BM process

### PR DESCRIPTION
**Pull request by gabehassler**
Major changes (from last pull request):
- Fixing bug (and adding test) with random root in `ParamsMultiBM`.
- Adding shift for `ParamsMultiBM
- jldoctests for `simulate()` and `ParamsMultiBM` 
- Memory efficient calculations in `ParamsMultiBM`

The only changes that may affect users is that `getShiftValue()` now returns a 2-d array instead of a 1-d array. I had to make a small change to `test_simulate.jl` to accommodate this, but otherwise everything is the same. Note that for a 1-d process the array still only has one column, it's just an `Array{Float64, 2}` instead of an `Array{Float64, 1}`. Let me know if that's a problem and I'll figure out how to keep the original behavior.

### CODE REVIEW

**Comment by pbastide** [comment]
Thank you @gabehassler, it looks great to me too !

Maybe one possible easy consistency test to add could be to simulate with a `ParamMultiBM` with dimension 1, and check that the results are consistent with a `ParamBM` ?

**Comment by cecileane** [comment]
So I added a test like you suggested Paul.

In doing so, I realized that one shift is not used at all (unless I'm mistaken). It is set at the root node when the simulator is set up. When "shown", it is said to be on edge `-1`, but there aren't any. It's because the root has no parent edge. I added a note about this in one of the docstrings. But I wonder if the simulator should be either of the 2 options below should be done:
1. refuse to construct a simulator (or even a `shiftNet`) with a shift at the root node, or
2. add the shift at the root node to the overall mean μ.

I am totally fine with option 1, but I didn't make the effort to implement it.

**Comment by pbastide** [comment]
Indeed, this looks like a hole in the simulation code ! Thank you for picking up on it.

I just did a commit to implement option 1.

I do the check at the simulation level, as this is when the shift is really a problem.

Actually, when building the `ShiftNet` object, we never check that the tree is rooted. I'm not sure that this is a problem though: a net with shifts could exist unrooted (for unknown future applications?), although it cannot be used for simulations.

But maybe that is a bit far-fetched, and we want to test directly in `ShiftNet` that the tree is rooted, and that there is no shift above the root ?

**Comment by cecileane** [comment]
Beautiful, thank you!

My only concern is that `net.isRooted` is rarely ever used (or updated) in other parts of the code. The root is determined by the value of `net.root`. What matters, is that edges have been directed away from root (with `directEdges!` if need be). Edges are all directed away from the root right after a phylogeny is read from newick string. But if a modification was made (like a change to the value of `net.root`), then we need to call `directEdges!` to update the direction of edges accordingly. The functions `rootonedge!` and `rootatnode!` direct edges appropriately.

Since folks doing comparative analyses don't typically do NNIs or other major transformations to their phylogenies, or they would change the root with `rootonedge!` and `rootatnode!`, I am not concerned.

Can I "squash and merge", Paul, or do you want to do it? I hope the 'squash' can do a rebase, to leave a clean git history.

**Comment by pbastide** [comment]
For my own education: is there already a simple test to check that the network is "ready for preorder" (with directed edges) ?

But I agree the typical PCM user should not encounter these kind of problems (or that would be the sign that something else probably went wrong somewhere before calling `simulate`).

Please go ahead and do the squash and merge when you're ready.

**Comment by cecileane** [comment]
Applying `directEdges!` provides a test: if all edges were directed away from the root, then nothing changes. If edges were misdirected, then their direction is updated. If `net.root` is not admissible, in the sense that it is below a hybrid node, then `directEdges!` throws a `RootMismatch` exception. So we can use `directEdges!` within a try/catch statement and check to see if any `RootMismatch` error comes up. This is done within `rootonedge!` and `rootatnode!`.

So I'll go away with the squash & merge. Thank you @pbastide and @gabehassler !

**Comment by cecileane** [comment]
replaces #122

**Comment by gabehassler** [comment]
Sorry for being late to the conversation, I was out of town last weekend and am just now catching back up on work. Thanks @cecileane and @pbastide for handling the remaining issues!

**Pull request merged**
