### PR TITLE
bug fix for biconnected components

### PR DESCRIPTION
**Pull request by cecileane**
fixes bug in biconnectedComponents, which occurred when the network has a 2-cycle, aka parallel edges.
tests on this were:
- moved to appropriate file
- expanded with 2-cycles cases, as a standalone blob or within a larger blob, possibly above the LSA
- expanded with extra root edge above the LSA

@fogg-uw: could you please see what you get with this version, for more thorough testing?

### CODE REVIEW

**Comment by cecileane** [comment]
@crsl4 : this PR would add a new section in the documentation ([preview here](https://crsl4.github.io/PhyloNetworks.jl/previews/PR182/man/netmanipulation/)) to list some utilities that the package has. I've heard from people who wanted to do some of these things and didn't know they were available. Would you mind looking at this new section, and sending feedback if you have any?

**Comment by fogg-uw** [comment]
> fixes bug in biconnectedComponents, which occurred when the network has a 2-cycle, aka parallel edges. tests on this were:
> 
> * moved to appropriate file
> * expanded with 2-cycles cases, as a standalone blob or within a larger blob, possibly above the LSA
> * expanded with extra root edge above the LSA
> 
> @fogg-uw: could you please see what you get with this version, for more thorough testing?

working on it now.

**Comment by fogg-uw** [comment]
> > fixes bug in biconnectedComponents, which occurred when the network has a 2-cycle, aka parallel edges. tests on this were:
> > 
> > * moved to appropriate file
> > * expanded with 2-cycles cases, as a standalone blob or within a larger blob, possibly above the LSA
> > * expanded with extra root edge above the LSA
> > 
> > @fogg-uw: could you please see what you get with this version, for more thorough testing?
> 
> working on it now.

here's an example of a network with both 2-cycles / parallel edges and structure above the LSA:

"((((((((t2:0.1628395387,#H25:0.0::0.2968210073):0.2645548417)#H22:0.02536997697::0.795811356,#H22:0.02536997697::0.204188644):0.1317061756,(((t6:0.07594995648,#H28:0.0::0.08108831872):0.0868895822)#H25:0.0::0.7031789927,(t10:0.07594995648)#H28:0.0868895822::0.9189116813):0.42163099427):0.06389243977,(t7:0.6483629727)#H14:0.0::0.804884407):0.3815006939,#H14:0.3815006939::0.195115593):0.1736407166)#H10:0.6477251715::0.8209544283,#H10:0.6477251715::0.1790455717);"

I checked biconnectedComponents and deleteaboveLSA! on this network and they both seem to be working as desired.

For more testing, here are some statistics about 44,730 quartet networks that i simulated using SiPhyNetworks:

Number of networks with a 2-cycle: 0 before bcc fix, 4,508 after bcc fix, 2,091 after bcc fix + delete above LSA
Number of networks with both a 3 blob and a 4 blob: 70 before bcc fix, 69 after bcc fix, 0 after bcc fix + delete above LSA
Number of networks with a 5-blob: 969 before bcc fix, 654 after bcc fix, 0 after bcc fix + delete above LSA

In this table, networks with a 2-cycle appear after the biconnected components fix, where they did not before.  Thus, the biconnected components may be working.

Also in this table, quartet networks with a 3-blob and a 4-blob, and quartet networks with a 5-blob, disappear after deleting structure above the LSA.  LSA quartet networks should have neither of those two structures. Thus, deleteaboveLSA! may be working.

Therefore, the changes in this pull request appear to be good.

**Comment by cecileane** [comment]
Wow, thanks for such a thorough investigation @fogg-uw ! 🎉

**Comment by cecileane** [comment]
> this PR would add a new section in the documentation ([preview here](https://crsl4.github.io/PhyloNetworks.jl/previews/PR182/man/netmanipulation/)) ...

@crsl4 : I could move this change to a new PR, or remove it altogether if you think it's redundant with the "Library" section of the documentation.

**Pull request merged**
